create table articulos (
	id INT,
	nombre VARCHAR(50),
	precio VARCHAR(50)
);
insert into articulos (id, nombre, precio) values (1, 'Spice - Peppercorn Melange', '€20,68');
insert into articulos (id, nombre, precio) values (2, 'Rice - Basmati', '€59,22');
insert into articulos (id, nombre, precio) values (3, 'Chocolate Bar - Reese Pieces', '€50,42');
insert into articulos (id, nombre, precio) values (4, 'Lotus Root', '€77,24');
insert into articulos (id, nombre, precio) values (5, 'Saskatoon Berries - Frozen', '€80,59');
insert into articulos (id, nombre, precio) values (6, 'Wine - White, Lindemans Bin 95', '€86,79');
insert into articulos (id, nombre, precio) values (7, 'Sloe Gin - Mcguinness', '€30,16');
insert into articulos (id, nombre, precio) values (8, 'Bread - Pumpernickle, Rounds', '€38,72');
insert into articulos (id, nombre, precio) values (9, 'Coffee Cup 12oz 5342cd', '€30,68');
insert into articulos (id, nombre, precio) values (10, 'Cream - 10%', '€25,48');
insert into articulos (id, nombre, precio) values (11, 'Green Tea Refresher', '€16,18');
insert into articulos (id, nombre, precio) values (12, 'Vanilla Beans', '€35,45');
insert into articulos (id, nombre, precio) values (13, 'Honey - Liquid', '€16,02');
insert into articulos (id, nombre, precio) values (14, 'Cheese - Mix', '€63,91');
insert into articulos (id, nombre, precio) values (15, 'Lamb - Bones', '€20,76');
insert into articulos (id, nombre, precio) values (16, 'Potato - Sweet', '€88,53');
insert into articulos (id, nombre, precio) values (17, 'Anchovy Paste - 56 G Tube', '€67,45');
insert into articulos (id, nombre, precio) values (18, 'Island Oasis - Magarita Mix', '€84,73');
insert into articulos (id, nombre, precio) values (19, 'Cheese - St. Andre', '€95,52');
insert into articulos (id, nombre, precio) values (20, 'Cheese - Parmesan Grated', '€26,71');
insert into articulos (id, nombre, precio) values (21, 'Bread - Pain Au Liat X12', '€52,55');
insert into articulos (id, nombre, precio) values (22, 'Pernod', '€52,66');
insert into articulos (id, nombre, precio) values (23, 'Tart Shells - Sweet, 3', '€32,44');
insert into articulos (id, nombre, precio) values (24, 'Sorrel - Fresh', '€48,10');
insert into articulos (id, nombre, precio) values (25, 'Bread - Petit Baguette', '€21,59');
insert into articulos (id, nombre, precio) values (26, 'Wine - Bourgogne 2002, La', '€36,50');
insert into articulos (id, nombre, precio) values (27, 'Grouper - Fresh', '€28,69');
insert into articulos (id, nombre, precio) values (28, 'Piping - Bags Quizna', '€77,74');
insert into articulos (id, nombre, precio) values (29, 'Flour - Semolina', '€74,79');
insert into articulos (id, nombre, precio) values (30, 'Yogurt - Banana, 175 Gr', '€69,85');
insert into articulos (id, nombre, precio) values (31, 'Chickensplit Half', '€97,38');
insert into articulos (id, nombre, precio) values (32, 'Sambuca - Ramazzotti', '€28,84');
insert into articulos (id, nombre, precio) values (33, 'Chicken - Livers', '€46,67');
insert into articulos (id, nombre, precio) values (34, 'Broom - Angled', '€90,22');
insert into articulos (id, nombre, precio) values (35, 'Galliano', '€83,83');
insert into articulos (id, nombre, precio) values (36, 'Salmon - Canned', '€22,62');
insert into articulos (id, nombre, precio) values (37, 'Orange - Blood', '€88,57');
insert into articulos (id, nombre, precio) values (38, 'Jam - Marmalade, Orange', '€85,51');
insert into articulos (id, nombre, precio) values (39, 'Noodles - Cellophane, Thin', '€38,32');
insert into articulos (id, nombre, precio) values (40, 'Chilli Paste, Hot Sambal Oelek', '€60,41');
insert into articulos (id, nombre, precio) values (41, 'Zucchini - Yellow', '€67,37');
insert into articulos (id, nombre, precio) values (42, 'Stainless Steel Cleaner Vision', '€24,82');
insert into articulos (id, nombre, precio) values (43, 'Cod - Black Whole Fillet', '€34,88');
insert into articulos (id, nombre, precio) values (44, 'Sausage - Andouille', '€40,86');
insert into articulos (id, nombre, precio) values (45, 'Shrimp - 16 - 20 Cooked, Peeled', '€82,20');
insert into articulos (id, nombre, precio) values (46, 'Mussels - Cultivated', '€64,66');
insert into articulos (id, nombre, precio) values (47, 'Pasta - Canelloni', '€25,93');
insert into articulos (id, nombre, precio) values (48, 'Crab - Dungeness, Whole', '€44,88');
insert into articulos (id, nombre, precio) values (49, 'Coffee - Espresso', '€19,64');
insert into articulos (id, nombre, precio) values (50, 'Chips - Potato Jalapeno', '€92,19');
insert into articulos (id, nombre, precio) values (51, 'Squash - Pepper', '€31,87');
insert into articulos (id, nombre, precio) values (52, 'Numi - Assorted Teas', '€40,86');
insert into articulos (id, nombre, precio) values (53, 'Milk 2% 500 Ml', '€81,44');
insert into articulos (id, nombre, precio) values (54, 'Pork - Bacon, Sliced', '€48,87');
insert into articulos (id, nombre, precio) values (55, 'Pastry - Chocolate Marble Tea', '€48,07');
insert into articulos (id, nombre, precio) values (56, 'Salt - Table', '€65,15');
insert into articulos (id, nombre, precio) values (57, 'Tabasco Sauce, 2 Oz', '€21,80');
insert into articulos (id, nombre, precio) values (58, 'Pasta - Linguini, Dry', '€62,67');
insert into articulos (id, nombre, precio) values (59, 'Wine - Stoneliegh Sauvignon', '€38,75');
insert into articulos (id, nombre, precio) values (60, 'Longos - Greek Salad', '€81,98');
insert into articulos (id, nombre, precio) values (61, 'Lamb - Whole, Fresh', '€75,37');
insert into articulos (id, nombre, precio) values (62, 'Foam Dinner Plate', '€28,58');
insert into articulos (id, nombre, precio) values (63, 'Chickensplit Half', '€25,28');
insert into articulos (id, nombre, precio) values (64, 'Flour - Masa De Harina Mexican', '€37,84');
insert into articulos (id, nombre, precio) values (65, 'Mix - Cocktail Strawberry Daiquiri', '€16,89');
insert into articulos (id, nombre, precio) values (66, 'Broom Handle', '€50,18');
insert into articulos (id, nombre, precio) values (67, 'Dried Figs', '€54,59');
insert into articulos (id, nombre, precio) values (68, 'Beef - Ground Lean Fresh', '€20,13');
insert into articulos (id, nombre, precio) values (69, 'Oven Mitts - 15 Inch', '€30,27');
insert into articulos (id, nombre, precio) values (70, 'Vaccum Bag - 14x20', '€77,74');
insert into articulos (id, nombre, precio) values (71, 'Veal - Loin', '€74,48');
insert into articulos (id, nombre, precio) values (72, 'Browning Caramel Glace', '€23,59');
insert into articulos (id, nombre, precio) values (73, 'Cup - Translucent 7 Oz Clear', '€34,31');
insert into articulos (id, nombre, precio) values (74, 'Carbonated Water - Blackberry', '€69,11');
insert into articulos (id, nombre, precio) values (75, 'Pepper - Red, Finger Hot', '€78,75');
insert into articulos (id, nombre, precio) values (76, 'Dill Weed - Dry', '€86,53');
insert into articulos (id, nombre, precio) values (77, 'Hummus - Spread', '€52,15');
insert into articulos (id, nombre, precio) values (78, 'Flour - Masa De Harina Mexican', '€49,36');
insert into articulos (id, nombre, precio) values (79, 'Cabbage - Green', '€56,70');
insert into articulos (id, nombre, precio) values (80, 'Milk 2% 500 Ml', '€82,03');
insert into articulos (id, nombre, precio) values (81, 'Cheese - Oka', '€91,49');
insert into articulos (id, nombre, precio) values (82, 'Bowl 12 Oz - Showcase 92012', '€54,33');
insert into articulos (id, nombre, precio) values (83, 'Horseradish Root', '€96,31');
insert into articulos (id, nombre, precio) values (84, 'Tart Shells - Sweet, 2', '€19,45');
insert into articulos (id, nombre, precio) values (85, 'Lemonade - Island Tea, 591 Ml', '€47,48');
insert into articulos (id, nombre, precio) values (86, 'Duck - Legs', '€81,88');
insert into articulos (id, nombre, precio) values (87, 'Pail For Lid 1537', '€59,32');
insert into articulos (id, nombre, precio) values (88, 'Sauce - Plum', '€52,13');
insert into articulos (id, nombre, precio) values (89, 'Allspice - Jamaican', '€92,95');
insert into articulos (id, nombre, precio) values (90, 'Juice - Ocean Spray Cranberry', '€88,97');
insert into articulos (id, nombre, precio) values (91, 'Orange - Tangerine', '€87,54');
insert into articulos (id, nombre, precio) values (92, 'Extract - Vanilla,artificial', '€18,19');
insert into articulos (id, nombre, precio) values (93, 'Peach - Fresh', '€33,30');
insert into articulos (id, nombre, precio) values (94, 'Mangostein', '€48,34');
insert into articulos (id, nombre, precio) values (95, 'Table Cloth 54x54 Colour', '€79,07');
insert into articulos (id, nombre, precio) values (96, 'External Supplier', '€78,77');
insert into articulos (id, nombre, precio) values (97, 'Soho Lychee Liqueur', '€80,80');
insert into articulos (id, nombre, precio) values (98, 'Cheese - Marble', '€93,87');
insert into articulos (id, nombre, precio) values (99, 'Bacardi Raspberry', '€47,82');
insert into articulos (id, nombre, precio) values (100, 'Lamb Rack Frenched Australian', '€75,86');
insert into articulos (id, nombre, precio) values (101, 'Butter Balls Salted', '€58,30');
insert into articulos (id, nombre, precio) values (102, 'Tortillas - Flour, 10', '€98,17');
insert into articulos (id, nombre, precio) values (103, 'Pasta - Lasagna, Dry', '€47,23');
insert into articulos (id, nombre, precio) values (104, 'Beer - Original Organic Lager', '€55,68');
insert into articulos (id, nombre, precio) values (105, 'Beans - Fava Fresh', '€39,32');
insert into articulos (id, nombre, precio) values (106, 'Juice - Ocean Spray Cranberry', '€87,18');
insert into articulos (id, nombre, precio) values (107, 'Lamb - Whole Head Off,nz', '€98,16');
insert into articulos (id, nombre, precio) values (108, 'Scallops - Live In Shell', '€65,01');
insert into articulos (id, nombre, precio) values (109, 'Wine - Fume Blanc Fetzer', '€86,55');
insert into articulos (id, nombre, precio) values (110, 'Bread - Multigrain', '€87,85');
insert into articulos (id, nombre, precio) values (111, 'Chocolate - Pistoles, White', '€41,98');
insert into articulos (id, nombre, precio) values (112, 'Anchovy Paste - 56 G Tube', '€59,49');
insert into articulos (id, nombre, precio) values (113, 'Wine - Rhine Riesling Wolf Blass', '€71,07');
insert into articulos (id, nombre, precio) values (114, 'Beer - Sleeman Fine Porter', '€43,80');
insert into articulos (id, nombre, precio) values (115, 'Banana', '€53,48');
insert into articulos (id, nombre, precio) values (116, 'Quail - Jumbo', '€42,57');
insert into articulos (id, nombre, precio) values (117, 'Soup Campbells Beef With Veg', '€94,29');
insert into articulos (id, nombre, precio) values (118, 'Flour - Buckwheat, Dark', '€23,36');
insert into articulos (id, nombre, precio) values (119, 'Amarula Cream', '€46,52');
insert into articulos (id, nombre, precio) values (120, 'Wine - Bouchard La Vignee Pinot', '€40,09');
insert into articulos (id, nombre, precio) values (121, 'Coffee Guatemala Dark', '€76,27');
insert into articulos (id, nombre, precio) values (122, 'Bagel - Whole White Sesame', '€51,40');
insert into articulos (id, nombre, precio) values (123, 'Russian Prince', '€66,36');
insert into articulos (id, nombre, precio) values (124, '7up Diet, 355 Ml', '€64,68');
insert into articulos (id, nombre, precio) values (125, 'Cauliflower', '€76,58');
insert into articulos (id, nombre, precio) values (126, 'Pasta - Penne, Lisce, Dry', '€22,59');
insert into articulos (id, nombre, precio) values (127, 'Sage - Rubbed', '€58,57');
insert into articulos (id, nombre, precio) values (128, 'Wine - Puligny Montrachet A.', '€64,19');
insert into articulos (id, nombre, precio) values (129, 'Ham - Procutinni', '€83,22');
insert into articulos (id, nombre, precio) values (130, 'Beans - Green', '€63,16');
insert into articulos (id, nombre, precio) values (131, 'Cleaner - Comet', '€32,61');
insert into articulos (id, nombre, precio) values (132, 'Bread - Olive', '€89,00');
insert into articulos (id, nombre, precio) values (133, 'Salt - Seasoned', '€16,26');
insert into articulos (id, nombre, precio) values (134, 'Broom - Corn', '€41,25');
insert into articulos (id, nombre, precio) values (135, 'Sugar - Brown', '€87,69');
insert into articulos (id, nombre, precio) values (136, 'Wine - Guy Sage Touraine', '€63,13');
insert into articulos (id, nombre, precio) values (137, 'Plate Pie Foil', '€77,78');
insert into articulos (id, nombre, precio) values (138, 'Brandy - Bar', '€73,55');
insert into articulos (id, nombre, precio) values (139, 'Cumin - Whole', '€75,69');
insert into articulos (id, nombre, precio) values (140, 'Nut - Hazelnut, Whole', '€36,48');
insert into articulos (id, nombre, precio) values (141, 'Browning Caramel Glace', '€49,03');
insert into articulos (id, nombre, precio) values (142, 'Rappini - Andy Boy', '€87,40');
insert into articulos (id, nombre, precio) values (143, 'Veal - Sweetbread', '€40,65');
insert into articulos (id, nombre, precio) values (144, 'Jameson - Irish Whiskey', '€90,03');
insert into articulos (id, nombre, precio) values (145, 'Appetizer - Sausage Rolls', '€21,67');
insert into articulos (id, nombre, precio) values (146, 'Wine - Malbec Trapiche Reserve', '€41,99');
insert into articulos (id, nombre, precio) values (147, 'Icecream - Dstk Strw Chseck', '€23,40');
insert into articulos (id, nombre, precio) values (148, 'Bread - 10 Grain', '€64,10');
insert into articulos (id, nombre, precio) values (149, 'Ice Cream - Turtles Stick Bar', '€74,91');
insert into articulos (id, nombre, precio) values (150, 'Wine - Rhine Riesling Wolf Blass', '€93,36');
insert into articulos (id, nombre, precio) values (151, 'Bread - Multigrain, Loaf', '€22,58');
insert into articulos (id, nombre, precio) values (152, 'Cheese - Grana Padano', '€20,34');
insert into articulos (id, nombre, precio) values (153, 'Beef - Kindney, Whole', '€53,47');
insert into articulos (id, nombre, precio) values (154, 'Tea - Lemon Scented', '€30,27');
insert into articulos (id, nombre, precio) values (155, 'Soup - Knorr, Chicken Gumbo', '€46,27');
insert into articulos (id, nombre, precio) values (156, 'Steampan - Half Size Shallow', '€36,87');
insert into articulos (id, nombre, precio) values (157, 'Bread - Olive', '€96,16');
insert into articulos (id, nombre, precio) values (158, 'Fond - Chocolate', '€84,61');
insert into articulos (id, nombre, precio) values (159, 'Lamb - Whole Head Off,nz', '€78,68');
insert into articulos (id, nombre, precio) values (160, 'Cheese - Brie, Cups 125g', '€76,30');
insert into articulos (id, nombre, precio) values (161, 'Ranchero - Primerba, Paste', '€80,10');
insert into articulos (id, nombre, precio) values (162, 'Flower - Leather Leaf Fern', '€88,74');
insert into articulos (id, nombre, precio) values (163, 'Radish - Pickled', '€17,30');
insert into articulos (id, nombre, precio) values (164, 'Steampan - Lid For Half Size', '€18,19');
insert into articulos (id, nombre, precio) values (165, 'Cheese - Brick With Onion', '€47,86');
insert into articulos (id, nombre, precio) values (166, 'Truffle Shells - White Chocolate', '€35,53');
insert into articulos (id, nombre, precio) values (167, 'Food Colouring - Green', '€22,81');
insert into articulos (id, nombre, precio) values (168, 'Tofu - Soft', '€48,27');
insert into articulos (id, nombre, precio) values (169, 'Chocolate - Pistoles, White', '€86,21');
insert into articulos (id, nombre, precio) values (170, 'Plastic Wrap', '€28,01');
insert into articulos (id, nombre, precio) values (171, 'Beer - Corona', '€28,82');
insert into articulos (id, nombre, precio) values (172, 'Beef - Ox Tail, Frozen', '€44,63');
insert into articulos (id, nombre, precio) values (173, 'Cup Translucent 9 Oz', '€58,53');
insert into articulos (id, nombre, precio) values (174, 'Daikon Radish', '€62,37');
insert into articulos (id, nombre, precio) values (175, 'Mustard - Dry, Powder', '€23,80');
insert into articulos (id, nombre, precio) values (176, 'Bar Mix - Pina Colada, 355 Ml', '€89,50');
insert into articulos (id, nombre, precio) values (177, 'Wine - Saint Emilion Calvet', '€41,23');
insert into articulos (id, nombre, precio) values (178, 'Clam Nectar', '€62,66');
insert into articulos (id, nombre, precio) values (179, 'Scampi Tail', '€66,36');
insert into articulos (id, nombre, precio) values (180, 'Energy Drink Bawls', '€54,79');
insert into articulos (id, nombre, precio) values (181, 'Ketchup - Tomato', '€95,27');
insert into articulos (id, nombre, precio) values (182, 'Scotch - Queen Anne', '€85,21');
insert into articulos (id, nombre, precio) values (183, 'Rice - Basmati', '€61,89');
insert into articulos (id, nombre, precio) values (184, 'Toothpick Frilled', '€61,16');
insert into articulos (id, nombre, precio) values (185, 'Wine - Chenin Blanc K.w.v.', '€22,64');
insert into articulos (id, nombre, precio) values (186, 'Pate - Cognac', '€87,34');
insert into articulos (id, nombre, precio) values (187, 'Tuna - Canned, Flaked, Light', '€41,83');
insert into articulos (id, nombre, precio) values (188, 'Pepper - Pablano', '€32,80');
insert into articulos (id, nombre, precio) values (189, 'Wine - Rubyport', '€96,90');
insert into articulos (id, nombre, precio) values (190, 'Chevere Logs', '€59,90');
insert into articulos (id, nombre, precio) values (191, 'Soup - Knorr, French Onion', '€64,06');
insert into articulos (id, nombre, precio) values (192, 'Sour Cream', '€66,60');
insert into articulos (id, nombre, precio) values (193, 'Pie Shells 10', '€24,02');
insert into articulos (id, nombre, precio) values (194, 'Contreau', '€57,31');
insert into articulos (id, nombre, precio) values (195, 'Muffin Batt - Ban Dream Zero', '€22,91');
insert into articulos (id, nombre, precio) values (196, 'Milk - Skim', '€65,43');
insert into articulos (id, nombre, precio) values (197, 'Pears - Anjou', '€77,83');
insert into articulos (id, nombre, precio) values (198, 'Lemonade - Kiwi, 591 Ml', '€29,81');
insert into articulos (id, nombre, precio) values (199, 'Ice Cream - Life Savers', '€25,24');
insert into articulos (id, nombre, precio) values (200, 'Sproutsmustard Cress', '€88,23');
insert into articulos (id, nombre, precio) values (201, 'Wine - Toasted Head', '€74,34');
insert into articulos (id, nombre, precio) values (202, 'Cocoa Powder - Natural', '€52,28');
insert into articulos (id, nombre, precio) values (203, 'Crab - Imitation Flakes', '€74,63');
insert into articulos (id, nombre, precio) values (204, 'Wine - Rioja Campo Viejo', '€59,10');
insert into articulos (id, nombre, precio) values (205, 'Apples - Sliced / Wedge', '€85,47');
insert into articulos (id, nombre, precio) values (206, 'Curry Paste - Green Masala', '€59,71');
insert into articulos (id, nombre, precio) values (207, 'Wine - Red, Marechal Foch', '€36,79');
insert into articulos (id, nombre, precio) values (208, 'Mcguinness - Blue Curacao', '€15,45');
insert into articulos (id, nombre, precio) values (209, 'Arctic Char - Fresh, Whole', '€71,06');
insert into articulos (id, nombre, precio) values (210, 'Pepper - White, Ground', '€76,36');
insert into articulos (id, nombre, precio) values (211, 'Rice - Wild', '€49,86');
insert into articulos (id, nombre, precio) values (212, 'Guinea Fowl', '€48,90');
insert into articulos (id, nombre, precio) values (213, 'Bulgar', '€16,09');
insert into articulos (id, nombre, precio) values (214, 'Sage - Rubbed', '€59,13');
insert into articulos (id, nombre, precio) values (215, 'Pork - Backs - Boneless', '€57,25');
insert into articulos (id, nombre, precio) values (216, 'Chef Hat 20cm', '€91,22');
insert into articulos (id, nombre, precio) values (217, 'Sauce - Apple, Unsweetened', '€80,60');
insert into articulos (id, nombre, precio) values (218, 'Fudge - Cream Fudge', '€54,78');
insert into articulos (id, nombre, precio) values (219, 'Ice Cream Bar - Oreo Sandwich', '€61,87');
insert into articulos (id, nombre, precio) values (220, 'Potatoes - Fingerling 4 Oz', '€43,04');
insert into articulos (id, nombre, precio) values (221, 'Kohlrabi', '€55,49');
insert into articulos (id, nombre, precio) values (222, 'Worcestershire Sauce', '€45,16');
insert into articulos (id, nombre, precio) values (223, 'Flour - Fast / Rapid', '€39,47');
insert into articulos (id, nombre, precio) values (224, 'Venison - Liver', '€89,52');
insert into articulos (id, nombre, precio) values (225, 'Towel Dispenser', '€55,90');
insert into articulos (id, nombre, precio) values (226, 'Cheese - Wine', '€52,15');
insert into articulos (id, nombre, precio) values (227, 'Sprouts - Alfalfa', '€29,81');
insert into articulos (id, nombre, precio) values (228, 'Cattail Hearts', '€89,40');
insert into articulos (id, nombre, precio) values (229, 'Cheese - Feta', '€62,36');
insert into articulos (id, nombre, precio) values (230, 'Beets', '€95,92');
insert into articulos (id, nombre, precio) values (231, 'Mousse - Passion Fruit', '€62,96');
insert into articulos (id, nombre, precio) values (232, 'Salmon - Canned', '€84,28');
insert into articulos (id, nombre, precio) values (233, 'Juice - Propel Sport', '€19,12');
insert into articulos (id, nombre, precio) values (234, 'Thyme - Fresh', '€95,35');
insert into articulos (id, nombre, precio) values (235, 'Rambutan', '€48,18');
insert into articulos (id, nombre, precio) values (236, 'Fudge - Chocolate Fudge', '€43,48');
insert into articulos (id, nombre, precio) values (237, 'Anchovy Fillets', '€87,70');
insert into articulos (id, nombre, precio) values (238, 'Crab - Dungeness, Whole', '€89,11');
insert into articulos (id, nombre, precio) values (239, 'Smoked Tongue', '€88,37');
insert into articulos (id, nombre, precio) values (240, 'Wine - Red, Antinori Santa', '€89,17');
insert into articulos (id, nombre, precio) values (241, 'Flour - Rye', '€77,40');
insert into articulos (id, nombre, precio) values (242, 'Sun - Dried Tomatoes', '€52,59');
insert into articulos (id, nombre, precio) values (243, '7up Diet, 355 Ml', '€58,87');
insert into articulos (id, nombre, precio) values (244, 'Tomatoes - Vine Ripe, Yellow', '€82,53');
insert into articulos (id, nombre, precio) values (245, 'Chicken - Breast, 5 - 7 Oz', '€42,32');
insert into articulos (id, nombre, precio) values (246, 'Tomato - Peeled Italian Canned', '€48,37');
insert into articulos (id, nombre, precio) values (247, 'Orange Roughy 6/8 Oz', '€70,35');
insert into articulos (id, nombre, precio) values (248, 'Steel Wool', '€24,72');
insert into articulos (id, nombre, precio) values (249, 'Apple - Northern Spy', '€76,66');
insert into articulos (id, nombre, precio) values (250, 'Wine - Montecillo Rioja Crianza', '€44,63');
insert into articulos (id, nombre, precio) values (251, 'Kiwano', '€78,75');
insert into articulos (id, nombre, precio) values (252, 'Soup - French Onion', '€87,53');
insert into articulos (id, nombre, precio) values (253, 'Coffee - Cafe Moreno', '€54,94');
insert into articulos (id, nombre, precio) values (254, 'Wine - Niagara Peninsula Vqa', '€77,97');
insert into articulos (id, nombre, precio) values (255, 'Lettuce - Arugula', '€16,07');
insert into articulos (id, nombre, precio) values (256, 'Foam Espresso Cup Plain White', '€73,68');
insert into articulos (id, nombre, precio) values (257, 'Cheese - Stilton', '€49,53');
insert into articulos (id, nombre, precio) values (258, 'Soup Campbells - Italian Wedding', '€88,09');
insert into articulos (id, nombre, precio) values (259, 'Pasta - Linguini, Dry', '€82,04');
insert into articulos (id, nombre, precio) values (260, 'Ice Cream Bar - Oreo Sandwich', '€50,19');
insert into articulos (id, nombre, precio) values (261, 'Table Cloth 54x72 Colour', '€35,64');
insert into articulos (id, nombre, precio) values (262, 'Lid - 0090 Clear', '€54,07');
insert into articulos (id, nombre, precio) values (263, 'Stock - Beef, Brown', '€97,62');
insert into articulos (id, nombre, precio) values (264, 'Nantucket - Carrot Orange', '€95,14');
insert into articulos (id, nombre, precio) values (265, 'Shrimp - Baby, Warm Water', '€95,36');
insert into articulos (id, nombre, precio) values (266, 'Cheese - Cottage Cheese', '€57,89');
insert into articulos (id, nombre, precio) values (267, 'Yogurt - Assorted Pack', '€68,89');
insert into articulos (id, nombre, precio) values (268, 'Butter - Salted', '€95,68');
insert into articulos (id, nombre, precio) values (269, 'Juice - Lagoon Mango', '€18,17');
insert into articulos (id, nombre, precio) values (270, 'Puree - Mocha', '€60,20');
insert into articulos (id, nombre, precio) values (271, 'Wine - Ej Gallo Sierra Valley', '€91,66');
insert into articulos (id, nombre, precio) values (272, 'Tomatoes Tear Drop Yellow', '€79,26');
insert into articulos (id, nombre, precio) values (273, 'Frangelico', '€85,72');
insert into articulos (id, nombre, precio) values (274, 'Fish - Base, Bouillion', '€27,30');
insert into articulos (id, nombre, precio) values (275, 'Syrup - Monin - Blue Curacao', '€39,60');
insert into articulos (id, nombre, precio) values (276, 'Beef - Rouladin, Sliced', '€40,49');
insert into articulos (id, nombre, precio) values (277, 'Wine - Zinfandel California 2002', '€85,25');
insert into articulos (id, nombre, precio) values (278, 'Beef - Flank Steak', '€64,12');
insert into articulos (id, nombre, precio) values (279, 'Shrimp - Black Tiger 26/30', '€97,47');
insert into articulos (id, nombre, precio) values (280, 'Soho Lychee Liqueur', '€50,97');
insert into articulos (id, nombre, precio) values (281, 'Wine - Sogrape Mateus Rose', '€65,99');
insert into articulos (id, nombre, precio) values (282, 'Cheese - Goat With Herbs', '€82,29');
insert into articulos (id, nombre, precio) values (283, 'Fireball Whisky', '€42,79');
insert into articulos (id, nombre, precio) values (284, 'Mustard - Individual Pkg', '€80,89');
insert into articulos (id, nombre, precio) values (285, 'Energy - Boo - Koo', '€72,97');
insert into articulos (id, nombre, precio) values (286, 'Beer - Heinekin', '€26,40');
insert into articulos (id, nombre, precio) values (287, 'Cake - Pancake', '€18,17');
insert into articulos (id, nombre, precio) values (288, 'Wine - Peller Estates Late', '€47,12');
insert into articulos (id, nombre, precio) values (289, 'Skewers - Bamboo', '€55,63');
insert into articulos (id, nombre, precio) values (290, 'Flower - Dish Garden', '€46,58');
insert into articulos (id, nombre, precio) values (291, 'Sparkling Wine - Rose, Freixenet', '€60,84');
insert into articulos (id, nombre, precio) values (292, 'Steamers White', '€35,26');
insert into articulos (id, nombre, precio) values (293, 'Mousse - Passion Fruit', '€23,79');
insert into articulos (id, nombre, precio) values (294, 'Trout - Rainbow, Frozen', '€26,19');
insert into articulos (id, nombre, precio) values (295, 'Pastry - Banana Tea Loaf', '€29,51');
insert into articulos (id, nombre, precio) values (296, 'Chicken - Thigh, Bone In', '€29,47');
insert into articulos (id, nombre, precio) values (297, 'Tea - Mint', '€38,34');
insert into articulos (id, nombre, precio) values (298, 'Syrup - Kahlua Chocolate', '€23,29');
insert into articulos (id, nombre, precio) values (299, 'Kiwano', '€59,10');
insert into articulos (id, nombre, precio) values (300, 'Sausage - Andouille', '€54,94');
insert into articulos (id, nombre, precio) values (301, 'Tea - Jasmin Green', '€47,81');
insert into articulos (id, nombre, precio) values (302, 'Pepper - Roasted Red', '€33,77');
insert into articulos (id, nombre, precio) values (303, 'Wine - Two Oceans Sauvignon', '€69,41');
insert into articulos (id, nombre, precio) values (304, 'Yogurt - Assorted Pack', '€46,63');
insert into articulos (id, nombre, precio) values (305, 'Muffin - Mix - Strawberry Rhubarb', '€27,98');
insert into articulos (id, nombre, precio) values (306, 'Jerusalem Artichoke', '€53,58');
insert into articulos (id, nombre, precio) values (307, 'Yogurt - Assorted Pack', '€73,05');
insert into articulos (id, nombre, precio) values (308, 'Cheese - Fontina', '€85,92');
insert into articulos (id, nombre, precio) values (309, 'Bread - Hamburger Buns', '€35,72');
insert into articulos (id, nombre, precio) values (310, 'Container - Clear 32 Oz', '€59,23');
insert into articulos (id, nombre, precio) values (311, 'Cabbage - Savoy', '€49,71');
insert into articulos (id, nombre, precio) values (312, 'Sprouts - Peppercress', '€39,66');
insert into articulos (id, nombre, precio) values (313, 'Tarts Assorted', '€70,91');
insert into articulos (id, nombre, precio) values (314, 'Shrimp - Black Tiger 6 - 8', '€98,16');
insert into articulos (id, nombre, precio) values (315, 'Arrowroot', '€81,97');
insert into articulos (id, nombre, precio) values (316, 'Ice Cream Bar - Oreo Cone', '€48,49');
insert into articulos (id, nombre, precio) values (317, 'Oil - Olive, Extra Virgin', '€49,35');
insert into articulos (id, nombre, precio) values (318, 'Rosemary - Dry', '€61,69');
insert into articulos (id, nombre, precio) values (319, 'Burger Veggie', '€17,04');
insert into articulos (id, nombre, precio) values (320, 'Bread - Burger', '€53,11');
insert into articulos (id, nombre, precio) values (321, 'Cheese - Gorgonzola', '€82,22');
insert into articulos (id, nombre, precio) values (322, 'Lettuce - Green Leaf', '€73,47');
insert into articulos (id, nombre, precio) values (323, 'Cookies - Englishbay Oatmeal', '€30,29');
insert into articulos (id, nombre, precio) values (324, 'Wine - Sake', '€68,16');
insert into articulos (id, nombre, precio) values (325, 'Wine - Periguita Fonseca', '€56,31');
insert into articulos (id, nombre, precio) values (326, 'Parasol Pick Stir Stick', '€68,37');
insert into articulos (id, nombre, precio) values (327, 'Lettuce - Lolla Rosa', '€49,90');
insert into articulos (id, nombre, precio) values (328, 'Red Pepper Paste', '€53,22');
insert into articulos (id, nombre, precio) values (329, 'Lamb - Shoulder', '€77,65');
insert into articulos (id, nombre, precio) values (330, 'Sauce - Vodka Blush', '€99,52');
insert into articulos (id, nombre, precio) values (331, 'Shrimp - Black Tiger 13/15', '€85,67');
insert into articulos (id, nombre, precio) values (332, 'Salmon Atl.whole 8 - 10 Lb', '€68,07');
insert into articulos (id, nombre, precio) values (333, 'Raisin - Dark', '€51,15');
insert into articulos (id, nombre, precio) values (334, 'Blueberries', '€29,45');
insert into articulos (id, nombre, precio) values (335, 'Lettuce - Spring Mix', '€25,54');
insert into articulos (id, nombre, precio) values (336, 'Olives - Kalamata', '€43,28');
insert into articulos (id, nombre, precio) values (337, 'Mop Head - Cotton, 24 Oz', '€74,62');
insert into articulos (id, nombre, precio) values (338, 'Halibut - Fletches', '€46,42');
insert into articulos (id, nombre, precio) values (339, 'Chick Peas - Dried', '€57,14');
insert into articulos (id, nombre, precio) values (340, 'Yams', '€73,62');
insert into articulos (id, nombre, precio) values (341, 'Cheese - Brie Roitelet', '€28,93');
insert into articulos (id, nombre, precio) values (342, 'Seabream Whole Farmed', '€60,13');
insert into articulos (id, nombre, precio) values (343, 'Yoghurt Tubes', '€74,75');
insert into articulos (id, nombre, precio) values (344, 'Pork - Ground', '€21,87');
insert into articulos (id, nombre, precio) values (345, 'Beer - Heinekin', '€66,54');
insert into articulos (id, nombre, precio) values (346, 'Chips Potato All Dressed - 43g', '€31,90');
insert into articulos (id, nombre, precio) values (347, 'Wine - White, Cooking', '€48,16');
insert into articulos (id, nombre, precio) values (348, 'Soup - Knorr, Veg / Beef', '€35,63');
insert into articulos (id, nombre, precio) values (349, 'Stock - Chicken, White', '€30,93');
insert into articulos (id, nombre, precio) values (350, 'Chocolate - Pistoles, Lactee, Milk', '€42,44');
insert into articulos (id, nombre, precio) values (351, 'Shrimp - Prawn', '€66,01');
insert into articulos (id, nombre, precio) values (352, 'Juice - Apple, 500 Ml', '€77,65');
insert into articulos (id, nombre, precio) values (353, 'Carbonated Water - Orange', '€97,90');
insert into articulos (id, nombre, precio) values (354, 'Tuna - Yellowfin', '€71,21');
insert into articulos (id, nombre, precio) values (355, 'Spinach - Frozen', '€42,05');
insert into articulos (id, nombre, precio) values (356, 'Milk - Buttermilk', '€75,77');
insert into articulos (id, nombre, precio) values (357, 'Pastry - Chocolate Chip Muffin', '€70,87');
insert into articulos (id, nombre, precio) values (358, 'Nantucket - 518ml', '€40,76');
insert into articulos (id, nombre, precio) values (359, 'Latex Rubber Gloves Size 9', '€51,95');
insert into articulos (id, nombre, precio) values (360, 'Wine - Ruffino Chianti', '€92,09');
insert into articulos (id, nombre, precio) values (361, 'Coconut Milk - Unsweetened', '€26,94');
insert into articulos (id, nombre, precio) values (362, 'Wine - Zinfandel Rosenblum', '€76,71');
insert into articulos (id, nombre, precio) values (363, 'Wine - Valpolicella Masi', '€51,36');
insert into articulos (id, nombre, precio) values (364, 'Wine - Chardonnay South', '€76,42');
insert into articulos (id, nombre, precio) values (365, 'Currants', '€56,48');
insert into articulos (id, nombre, precio) values (366, 'Sobe - Lizard Fuel', '€67,79');
insert into articulos (id, nombre, precio) values (367, 'Sweet Pea Sprouts', '€16,49');
insert into articulos (id, nombre, precio) values (368, 'Waffle Stix', '€83,21');
insert into articulos (id, nombre, precio) values (369, 'Oven Mitts 17 Inch', '€78,36');
insert into articulos (id, nombre, precio) values (370, 'Lamb - Sausage Casings', '€20,72');
insert into articulos (id, nombre, precio) values (371, 'Beets - Mini Golden', '€37,76');
insert into articulos (id, nombre, precio) values (372, 'Juice - Cranberry 284ml', '€48,62');
insert into articulos (id, nombre, precio) values (373, 'Lettuce - Iceberg', '€97,94');
insert into articulos (id, nombre, precio) values (374, 'Cheese - Grana Padano', '€44,06');
insert into articulos (id, nombre, precio) values (375, 'Longos - Greek Salad', '€71,42');
insert into articulos (id, nombre, precio) values (376, 'Muffin - Mix - Creme Brule 15l', '€62,88');
insert into articulos (id, nombre, precio) values (377, 'Tomatoes - Vine Ripe, Yellow', '€85,58');
insert into articulos (id, nombre, precio) values (378, 'Lemon Grass', '€21,86');
insert into articulos (id, nombre, precio) values (379, 'Muffin Mix - Morning Glory', '€54,70');
insert into articulos (id, nombre, precio) values (380, 'Yogurt - Plain', '€17,52');
insert into articulos (id, nombre, precio) values (381, 'Truffle - Whole Black Peeled', '€94,01');
insert into articulos (id, nombre, precio) values (382, 'Chevril', '€89,80');
insert into articulos (id, nombre, precio) values (383, 'Tea - Darjeeling, Azzura', '€71,49');
insert into articulos (id, nombre, precio) values (384, 'Duck - Breast', '€15,14');
insert into articulos (id, nombre, precio) values (385, 'Rambutan', '€30,81');
insert into articulos (id, nombre, precio) values (386, 'Water Chestnut - Canned', '€83,08');
insert into articulos (id, nombre, precio) values (387, 'Clams - Bay', '€89,10');
insert into articulos (id, nombre, precio) values (388, 'Oil - Food, Lacquer Spray', '€56,35');
insert into articulos (id, nombre, precio) values (389, 'Lamb - Shoulder, Boneless', '€23,60');
insert into articulos (id, nombre, precio) values (390, 'Sauce - Soya, Light', '€67,06');
insert into articulos (id, nombre, precio) values (391, 'Lettuce - Escarole', '€73,05');
insert into articulos (id, nombre, precio) values (392, 'Canada Dry', '€19,80');
insert into articulos (id, nombre, precio) values (393, 'Syrup - Pancake', '€56,43');
insert into articulos (id, nombre, precio) values (394, 'Wine - Vineland Estate Semi - Dry', '€71,92');
insert into articulos (id, nombre, precio) values (395, 'Corn Shoots', '€37,21');
insert into articulos (id, nombre, precio) values (396, 'Tomatoes - Grape', '€38,26');
insert into articulos (id, nombre, precio) values (397, 'Bread Fig And Almond', '€15,69');
insert into articulos (id, nombre, precio) values (398, 'Chef Hat 25cm', '€78,13');
insert into articulos (id, nombre, precio) values (399, 'Cucumber - Pickling Ontario', '€71,92');
insert into articulos (id, nombre, precio) values (400, 'Tarts Assorted', '€66,19');
insert into articulos (id, nombre, precio) values (401, 'Dill Weed - Dry', '€46,81');
insert into articulos (id, nombre, precio) values (402, 'Pepsi - Diet, 355 Ml', '€26,76');
insert into articulos (id, nombre, precio) values (403, 'Ostrich - Prime Cut', '€40,10');
insert into articulos (id, nombre, precio) values (404, 'Jack Daniels', '€57,45');
insert into articulos (id, nombre, precio) values (405, 'Food Colouring - Red', '€53,80');
insert into articulos (id, nombre, precio) values (406, 'Chick Peas - Dried', '€90,13');
insert into articulos (id, nombre, precio) values (407, 'Soup - Verve - Chipotle Chicken', '€27,39');
insert into articulos (id, nombre, precio) values (408, 'Cheese - Manchego, Spanish', '€87,00');
insert into articulos (id, nombre, precio) values (409, 'Coffee Beans - Chocolate', '€82,54');
insert into articulos (id, nombre, precio) values (410, 'Sugar - Invert', '€34,22');
insert into articulos (id, nombre, precio) values (411, 'Stock - Chicken, White', '€30,30');
insert into articulos (id, nombre, precio) values (412, 'Curry Powder Madras', '€35,56');
insert into articulos (id, nombre, precio) values (413, 'Marzipan 50/50', '€49,35');
insert into articulos (id, nombre, precio) values (414, 'Straw - Regular', '€47,28');
insert into articulos (id, nombre, precio) values (415, 'Mushroom - Morel Frozen', '€23,45');
insert into articulos (id, nombre, precio) values (416, 'Cheese - Brie, Cups 125g', '€81,52');
insert into articulos (id, nombre, precio) values (417, 'Sambuca - Opal Nera', '€26,32');
insert into articulos (id, nombre, precio) values (418, 'Table Cloth 144x90 White', '€52,10');
insert into articulos (id, nombre, precio) values (419, 'Raspberries - Frozen', '€65,56');
insert into articulos (id, nombre, precio) values (420, 'Quail - Eggs, Fresh', '€76,00');
insert into articulos (id, nombre, precio) values (421, 'Bread - White, Sliced', '€82,13');
insert into articulos (id, nombre, precio) values (422, 'Grenadine', '€99,28');
insert into articulos (id, nombre, precio) values (423, 'Mint - Fresh', '€29,48');
insert into articulos (id, nombre, precio) values (424, 'Wine - Casablanca Valley', '€28,60');
insert into articulos (id, nombre, precio) values (425, 'Muffin Hinge - 211n', '€37,40');
insert into articulos (id, nombre, precio) values (426, 'Wine - White, Pinot Grigio', '€99,55');
insert into articulos (id, nombre, precio) values (427, 'Potatoes - Yukon Gold, 80 Ct', '€50,36');
insert into articulos (id, nombre, precio) values (428, 'Bread - Multigrain, Loaf', '€49,27');
insert into articulos (id, nombre, precio) values (429, 'Juice - Pineapple, 48 Oz', '€17,42');
insert into articulos (id, nombre, precio) values (430, 'Hipnotiq Liquor', '€82,48');
insert into articulos (id, nombre, precio) values (431, 'Magnotta - Bel Paese White', '€90,47');
insert into articulos (id, nombre, precio) values (432, 'Lobster - Live', '€92,44');
insert into articulos (id, nombre, precio) values (433, 'Ecolab - Hobart Washarm End Cap', '€46,69');
insert into articulos (id, nombre, precio) values (434, 'Wine - Puligny Montrachet A.', '€20,35');
insert into articulos (id, nombre, precio) values (435, 'Wine - Guy Sage Touraine', '€32,47');
insert into articulos (id, nombre, precio) values (436, 'Bar - Granola Trail Mix Fruit Nut', '€33,31');
insert into articulos (id, nombre, precio) values (437, 'Calypso - Black Cherry Lemonade', '€63,49');
insert into articulos (id, nombre, precio) values (438, 'Coffee Decaf Colombian', '€95,03');
insert into articulos (id, nombre, precio) values (439, 'Langers - Ruby Red Grapfruit', '€60,61');
insert into articulos (id, nombre, precio) values (440, 'Pepper Squash', '€80,26');
insert into articulos (id, nombre, precio) values (441, 'Gatorade - Xfactor Berry', '€99,34');
insert into articulos (id, nombre, precio) values (442, 'Glass - Wine, Plastic, Clear 5 Oz', '€91,64');
insert into articulos (id, nombre, precio) values (443, 'Dried Cranberries', '€21,40');
insert into articulos (id, nombre, precio) values (444, 'Fish - Base, Bouillion', '€99,48');
insert into articulos (id, nombre, precio) values (445, 'Muffin Mix - Carrot', '€30,55');
insert into articulos (id, nombre, precio) values (446, 'Frangelico', '€47,62');
insert into articulos (id, nombre, precio) values (447, 'Cheese - Roquefort Pappillon', '€50,43');
insert into articulos (id, nombre, precio) values (448, 'Wine - Magnotta - Red, Baco', '€46,60');
insert into articulos (id, nombre, precio) values (449, 'Wine - Magnotta, Merlot Sr Vqa', '€72,08');
insert into articulos (id, nombre, precio) values (450, 'Noodles - Cellophane, Thin', '€97,52');
insert into articulos (id, nombre, precio) values (451, 'Rum - Mount Gay Eclipes', '€25,59');
insert into articulos (id, nombre, precio) values (452, 'Cookies - Assorted', '€24,49');
insert into articulos (id, nombre, precio) values (453, 'Appetizer - Cheese Bites', '€53,51');
insert into articulos (id, nombre, precio) values (454, 'Duck - Legs', '€15,86');
insert into articulos (id, nombre, precio) values (455, 'Mountain Dew', '€17,31');
insert into articulos (id, nombre, precio) values (456, 'Wine - Niagara Peninsula Vqa', '€74,00');
insert into articulos (id, nombre, precio) values (457, 'Butter - Unsalted', '€77,52');
insert into articulos (id, nombre, precio) values (458, 'Carbonated Water - Cherry', '€99,95');
insert into articulos (id, nombre, precio) values (459, 'Cheese - Ricotta', '€37,58');
insert into articulos (id, nombre, precio) values (460, 'Lidsoupcont Rp12dn', '€97,15');
insert into articulos (id, nombre, precio) values (461, 'Table Cloth 90x90 Colour', '€28,69');
insert into articulos (id, nombre, precio) values (462, 'Octopus - Baby, Cleaned', '€43,40');
insert into articulos (id, nombre, precio) values (463, 'Quiche Assorted', '€62,24');
insert into articulos (id, nombre, precio) values (464, 'Cape Capensis - Fillet', '€19,35');
insert into articulos (id, nombre, precio) values (465, 'Asparagus - Mexican', '€93,08');
insert into articulos (id, nombre, precio) values (466, 'Pepper - Chilli Seeds Mild', '€20,61');
insert into articulos (id, nombre, precio) values (467, 'Chicken - Leg / Back Attach', '€28,06');
insert into articulos (id, nombre, precio) values (468, 'Pepper - White, Whole', '€88,21');
insert into articulos (id, nombre, precio) values (469, 'Bread - Pumpernickel', '€24,28');
insert into articulos (id, nombre, precio) values (470, 'Carbonated Water - Strawberry', '€56,49');
insert into articulos (id, nombre, precio) values (471, 'Cheese - Marble', '€42,67');
insert into articulos (id, nombre, precio) values (472, 'Plaintain', '€81,09');
insert into articulos (id, nombre, precio) values (473, 'Creme De Cacao White', '€98,97');
insert into articulos (id, nombre, precio) values (474, 'Juice - Mango', '€84,15');
insert into articulos (id, nombre, precio) values (475, 'Chicken Thigh - Bone Out', '€50,87');
insert into articulos (id, nombre, precio) values (476, 'Snapple - Iced Tea Peach', '€85,21');
insert into articulos (id, nombre, precio) values (477, 'Glycerine', '€72,32');
insert into articulos (id, nombre, precio) values (478, 'Bread - Roll, Italian', '€79,16');
insert into articulos (id, nombre, precio) values (479, 'Spice - Paprika', '€54,76');
insert into articulos (id, nombre, precio) values (480, 'Potatoes - Yukon Gold 5 Oz', '€24,28');
insert into articulos (id, nombre, precio) values (481, 'Dasheen', '€60,54');
insert into articulos (id, nombre, precio) values (482, 'Seabream Whole Farmed', '€48,74');
insert into articulos (id, nombre, precio) values (483, 'Trout - Rainbow, Frozen', '€55,82');
insert into articulos (id, nombre, precio) values (484, 'Wine - White, Chardonnay', '€76,90');
insert into articulos (id, nombre, precio) values (485, 'Onions - Cippolini', '€64,07');
insert into articulos (id, nombre, precio) values (486, 'Cheese - Ricotta', '€64,53');
insert into articulos (id, nombre, precio) values (487, 'Cafe Royale', '€97,16');
insert into articulos (id, nombre, precio) values (488, 'Rice - Aborio', '€20,94');
insert into articulos (id, nombre, precio) values (489, 'Pastry - Apple Muffins - Mini', '€28,52');
insert into articulos (id, nombre, precio) values (490, 'Wine - Sake', '€76,34');
insert into articulos (id, nombre, precio) values (491, 'Soup - Campbells Beef Strogonoff', '€52,20');
insert into articulos (id, nombre, precio) values (492, 'Lamb - Whole, Fresh', '€64,25');
insert into articulos (id, nombre, precio) values (493, 'Appetizer - Mango Chevre', '€61,86');
insert into articulos (id, nombre, precio) values (494, 'Tea - Lemon Scented', '€18,61');
insert into articulos (id, nombre, precio) values (495, 'Pasta - Cheese / Spinach Bauletti', '€80,25');
insert into articulos (id, nombre, precio) values (496, 'Carbonated Water - White Grape', '€95,82');
insert into articulos (id, nombre, precio) values (497, 'Veal - Tenderloin, Untrimmed', '€92,54');
insert into articulos (id, nombre, precio) values (498, 'Buffalo - Tenderloin', '€96,18');
insert into articulos (id, nombre, precio) values (499, 'Soup Campbells Mexicali Tortilla', '€54,37');
insert into articulos (id, nombre, precio) values (500, 'Coffee - Irish Cream', '€88,55');
insert into articulos (id, nombre, precio) values (501, 'Mint - Fresh', '€42,01');
insert into articulos (id, nombre, precio) values (502, 'Appetizer - Mushroom Tart', '€53,52');
insert into articulos (id, nombre, precio) values (503, 'Lumpfish Black', '€60,16');
insert into articulos (id, nombre, precio) values (504, 'Cheese - Provolone', '€44,61');
insert into articulos (id, nombre, precio) values (505, 'Uniform Linen Charge', '€92,16');
insert into articulos (id, nombre, precio) values (506, 'Cheese - Manchego, Spanish', '€33,95');
insert into articulos (id, nombre, precio) values (507, 'Neckerchief Blck', '€22,29');
insert into articulos (id, nombre, precio) values (508, 'Wine - Chablis 2003 Champs', '€60,65');
insert into articulos (id, nombre, precio) values (509, 'Cheese - Mozzarella', '€52,67');
insert into articulos (id, nombre, precio) values (510, 'Wine - Jafflin Bourgongone', '€42,03');
insert into articulos (id, nombre, precio) values (511, 'Contreau', '€56,19');
insert into articulos (id, nombre, precio) values (512, 'Steam Pan - Half Size Deep', '€18,07');
insert into articulos (id, nombre, precio) values (513, 'Toamtoes 6x7 Select', '€96,66');
insert into articulos (id, nombre, precio) values (514, 'Graham Cracker Mix', '€85,30');
insert into articulos (id, nombre, precio) values (515, 'Lychee', '€47,94');
insert into articulos (id, nombre, precio) values (516, 'Table Cloth 53x53 White', '€63,27');
insert into articulos (id, nombre, precio) values (517, 'Shrimp - Baby, Cold Water', '€46,95');
insert into articulos (id, nombre, precio) values (518, 'Mushroom - Trumpet, Dry', '€48,51');
insert into articulos (id, nombre, precio) values (519, 'Cheese - Mozzarella', '€82,01');
insert into articulos (id, nombre, precio) values (520, 'Basil - Dry, Rubbed', '€17,32');
insert into articulos (id, nombre, precio) values (521, 'Pork - Ham, Virginia', '€74,29');
insert into articulos (id, nombre, precio) values (522, 'Lotus Root', '€59,15');
insert into articulos (id, nombre, precio) values (523, 'Water - San Pellegrino', '€52,40');
insert into articulos (id, nombre, precio) values (524, 'Gingerale - Schweppes, 355 Ml', '€41,12');
insert into articulos (id, nombre, precio) values (525, 'Wine - Sauvignon Blanc', '€72,13');
insert into articulos (id, nombre, precio) values (526, 'Flour - Semolina', '€64,65');
insert into articulos (id, nombre, precio) values (527, 'Petit Baguette', '€86,88');
insert into articulos (id, nombre, precio) values (528, 'Quail Eggs - Canned', '€68,32');
insert into articulos (id, nombre, precio) values (529, 'Parsley Italian - Fresh', '€48,93');
insert into articulos (id, nombre, precio) values (530, 'Apple - Fuji', '€65,49');
insert into articulos (id, nombre, precio) values (531, 'Pepper - Red Chili', '€94,75');
insert into articulos (id, nombre, precio) values (532, 'Flour Pastry Super Fine', '€93,18');
insert into articulos (id, nombre, precio) values (533, 'Pasta - Fusili Tri - Coloured', '€65,47');
insert into articulos (id, nombre, precio) values (534, 'Wine - Barossa Valley Estate', '€87,76');
insert into articulos (id, nombre, precio) values (535, 'Mushroom - Shitake, Dry', '€35,78');
insert into articulos (id, nombre, precio) values (536, 'Salmon Atl.whole 8 - 10 Lb', '€49,98');
insert into articulos (id, nombre, precio) values (537, 'Wine - Crozes Hermitage E.', '€59,05');
insert into articulos (id, nombre, precio) values (538, 'Ham - Procutinni', '€36,89');
insert into articulos (id, nombre, precio) values (539, 'Sobe - Berry Energy', '€75,49');
insert into articulos (id, nombre, precio) values (540, 'Spice - Chili Powder Mexican', '€21,53');
insert into articulos (id, nombre, precio) values (541, 'Cake - French Pear Tart', '€33,28');
insert into articulos (id, nombre, precio) values (542, 'Pear - Halves', '€85,18');
insert into articulos (id, nombre, precio) values (543, 'Steel Wool', '€99,66');
insert into articulos (id, nombre, precio) values (544, 'Tortillas - Flour, 10', '€31,13');
insert into articulos (id, nombre, precio) values (545, 'Isomalt', '€58,71');
insert into articulos (id, nombre, precio) values (546, 'Meldea Green Tea Liquor', '€73,60');
insert into articulos (id, nombre, precio) values (547, 'Tumeric', '€27,23');
insert into articulos (id, nombre, precio) values (548, 'Pepper - Green', '€32,96');
insert into articulos (id, nombre, precio) values (549, 'Veal - Slab Bacon', '€83,84');
insert into articulos (id, nombre, precio) values (550, 'Glove - Cutting', '€69,67');
insert into articulos (id, nombre, precio) values (551, 'Cornstarch', '€48,03');
insert into articulos (id, nombre, precio) values (552, 'Flour - Semolina', '€99,46');
insert into articulos (id, nombre, precio) values (553, 'Wine - Pinot Noir Pond Haddock', '€89,05');
insert into articulos (id, nombre, precio) values (554, 'Cheese - Cambozola', '€64,32');
insert into articulos (id, nombre, precio) values (555, 'Potatoes - Instant, Mashed', '€18,27');
insert into articulos (id, nombre, precio) values (556, 'Chocolate - Compound Coating', '€72,26');
insert into articulos (id, nombre, precio) values (557, 'Tomatoes', '€99,69');
insert into articulos (id, nombre, precio) values (558, 'Veal - Inside', '€98,89');
insert into articulos (id, nombre, precio) values (559, 'Energy - Boo - Koo', '€97,58');
insert into articulos (id, nombre, precio) values (560, 'Mushroom Morel Fresh', '€35,99');
insert into articulos (id, nombre, precio) values (561, 'Wine - Red, Antinori Santa', '€34,52');
insert into articulos (id, nombre, precio) values (562, 'Beer - Blue Light', '€90,89');
insert into articulos (id, nombre, precio) values (563, 'Cheese - Mozzarella, Buffalo', '€19,40');
insert into articulos (id, nombre, precio) values (564, 'Beer - True North Lager', '€47,84');
insert into articulos (id, nombre, precio) values (565, 'French Pastry - Mini Chocolate', '€47,91');
insert into articulos (id, nombre, precio) values (566, 'Latex Rubber Gloves Size 9', '€80,60');
insert into articulos (id, nombre, precio) values (567, 'Tuna - Salad Premix', '€96,63');
insert into articulos (id, nombre, precio) values (568, 'Beef - Short Ribs', '€92,32');
insert into articulos (id, nombre, precio) values (569, 'Mints - Striped Red', '€17,84');
insert into articulos (id, nombre, precio) values (570, 'Energy Drink Bawls', '€70,15');
insert into articulos (id, nombre, precio) values (571, 'Beans - Navy, Dry', '€72,11');
insert into articulos (id, nombre, precio) values (572, 'Wine - Champagne Brut Veuve', '€52,77');
insert into articulos (id, nombre, precio) values (573, 'Trueblue - Blueberry 12x473ml', '€81,32');
insert into articulos (id, nombre, precio) values (574, 'Cookie Choc', '€22,90');
insert into articulos (id, nombre, precio) values (575, 'Wine - Chateau Aqueria Tavel', '€41,41');
insert into articulos (id, nombre, precio) values (576, 'Steel Wool S.o.s', '€41,69');
insert into articulos (id, nombre, precio) values (577, 'Oneshot Automatic Soap System', '€24,83');
insert into articulos (id, nombre, precio) values (578, 'Carrots - Mini Red Organic', '€28,01');
insert into articulos (id, nombre, precio) values (579, 'Shrimp - Tiger 21/25', '€35,10');
insert into articulos (id, nombre, precio) values (580, 'Cheese - Brick With Pepper', '€59,30');
insert into articulos (id, nombre, precio) values (581, 'Chicken Breast Wing On', '€76,77');
insert into articulos (id, nombre, precio) values (582, 'Butter - Unsalted', '€23,46');
insert into articulos (id, nombre, precio) values (583, 'Chocolate - Mi - Amere Semi', '€60,78');
insert into articulos (id, nombre, precio) values (584, 'Sugar - Invert', '€22,73');
insert into articulos (id, nombre, precio) values (585, 'Poppy Seed', '€89,64');
insert into articulos (id, nombre, precio) values (586, 'Pork - European Side Bacon', '€44,13');
insert into articulos (id, nombre, precio) values (587, 'Onion Powder', '€47,52');
insert into articulos (id, nombre, precio) values (588, 'Butter - Pod', '€41,19');
insert into articulos (id, nombre, precio) values (589, 'Wine - Spumante Bambino White', '€20,23');
insert into articulos (id, nombre, precio) values (590, 'Wine - Magnotta - Cab Franc', '€33,71');
insert into articulos (id, nombre, precio) values (591, 'Red Snapper - Fresh, Whole', '€23,26');
insert into articulos (id, nombre, precio) values (592, 'Heavy Duty Dust Pan', '€24,42');
insert into articulos (id, nombre, precio) values (593, 'Honey - Lavender', '€78,33');
insert into articulos (id, nombre, precio) values (594, 'Pepper - Cubanelle', '€39,46');
insert into articulos (id, nombre, precio) values (595, 'Rhubarb', '€18,22');
insert into articulos (id, nombre, precio) values (596, 'Vermouth - Sweet, Cinzano', '€50,98');
insert into articulos (id, nombre, precio) values (597, 'Cookie Dough - Chocolate Chip', '€93,19');
insert into articulos (id, nombre, precio) values (598, 'Dried Figs', '€80,94');
insert into articulos (id, nombre, precio) values (599, 'Muffin Mix - Morning Glory', '€36,66');
insert into articulos (id, nombre, precio) values (600, 'Pasta - Fett Alfredo, Single Serve', '€71,17');
insert into articulos (id, nombre, precio) values (601, 'Halibut - Fletches', '€73,66');
insert into articulos (id, nombre, precio) values (602, 'Bread Roll Foccacia', '€50,11');
insert into articulos (id, nombre, precio) values (603, 'Dish Towel', '€69,07');
insert into articulos (id, nombre, precio) values (604, 'Sloe Gin - Mcguinness', '€93,84');
insert into articulos (id, nombre, precio) values (605, 'Southern Comfort', '€53,55');
insert into articulos (id, nombre, precio) values (606, 'Pastry - Cheese Baked Scones', '€48,66');
insert into articulos (id, nombre, precio) values (607, 'Island Oasis - Wildberry', '€33,75');
insert into articulos (id, nombre, precio) values (608, 'Sauce - Black Current, Dry Mix', '€99,20');
insert into articulos (id, nombre, precio) values (609, 'Sprouts - Alfalfa', '€71,27');
insert into articulos (id, nombre, precio) values (610, 'Garlic - Peeled', '€55,12');
insert into articulos (id, nombre, precio) values (611, 'Stock - Fish', '€51,34');
insert into articulos (id, nombre, precio) values (612, 'Oven Mitt - 13 Inch', '€76,22');
insert into articulos (id, nombre, precio) values (613, 'Bread - Bagels, Plain', '€27,96');
insert into articulos (id, nombre, precio) values (614, 'Soup - Campbells Mac N Cheese', '€23,17');
insert into articulos (id, nombre, precio) values (615, 'Onion Powder', '€21,98');
insert into articulos (id, nombre, precio) values (616, 'Potatoes - Purple, Organic', '€86,76');
insert into articulos (id, nombre, precio) values (617, 'Bread - Rosemary Focaccia', '€19,68');
insert into articulos (id, nombre, precio) values (618, 'Sobe - Liz Blizz', '€89,08');
insert into articulos (id, nombre, precio) values (619, 'Wine - Alicanca Vinho Verde', '€48,30');
insert into articulos (id, nombre, precio) values (620, 'Onions - White', '€24,98');
insert into articulos (id, nombre, precio) values (621, 'Bread - Italian Sesame Poly', '€59,97');
insert into articulos (id, nombre, precio) values (622, 'Piping Jelly - All Colours', '€49,28');
insert into articulos (id, nombre, precio) values (623, 'Rosemary - Primerba, Paste', '€80,46');
insert into articulos (id, nombre, precio) values (624, 'Muffin Carrot - Individual', '€40,20');
insert into articulos (id, nombre, precio) values (625, 'Wine - Cousino Macul Antiguas', '€63,16');
insert into articulos (id, nombre, precio) values (626, 'Soup - Campbells, Classic Chix', '€82,08');
insert into articulos (id, nombre, precio) values (627, 'Glaze - Apricot', '€25,70');
insert into articulos (id, nombre, precio) values (628, 'Yucca', '€29,86');
insert into articulos (id, nombre, precio) values (629, 'Beef - Chuck, Boneless', '€64,29');
insert into articulos (id, nombre, precio) values (630, 'Wine - Jafflin Bourgongone', '€76,90');
insert into articulos (id, nombre, precio) values (631, 'Bread Foccacia Whole', '€40,06');
insert into articulos (id, nombre, precio) values (632, 'Syrup - Monin, Amaretta', '€88,41');
insert into articulos (id, nombre, precio) values (633, 'Bread Sour Rolls', '€21,31');
insert into articulos (id, nombre, precio) values (634, 'Wasabi Powder', '€21,03');
insert into articulos (id, nombre, precio) values (635, 'Snapple - Iced Tea Peach', '€26,73');
insert into articulos (id, nombre, precio) values (636, 'Ham - Cooked Bayonne Tinned', '€68,69');
insert into articulos (id, nombre, precio) values (637, 'Soup Campbells Mexicali Tortilla', '€29,50');
insert into articulos (id, nombre, precio) values (638, 'Cafe Royale', '€92,19');
insert into articulos (id, nombre, precio) values (639, 'Oil - Food, Lacquer Spray', '€51,75');
insert into articulos (id, nombre, precio) values (640, 'Wine - Alsace Gewurztraminer', '€67,42');
insert into articulos (id, nombre, precio) values (641, 'Oregano - Fresh', '€97,85');
insert into articulos (id, nombre, precio) values (642, 'Veal - Eye Of Round', '€66,84');
insert into articulos (id, nombre, precio) values (643, 'Graham Cracker Mix', '€25,00');
insert into articulos (id, nombre, precio) values (644, 'Beef - Ground, Extra Lean, Fresh', '€88,91');
insert into articulos (id, nombre, precio) values (645, 'Nantucket - Orange Mango Cktl', '€23,43');
insert into articulos (id, nombre, precio) values (646, 'Bouillion - Fish', '€55,79');
insert into articulos (id, nombre, precio) values (647, 'Danishes - Mini Cheese', '€26,11');
insert into articulos (id, nombre, precio) values (648, 'Fondant - Icing', '€85,20');
insert into articulos (id, nombre, precio) values (649, 'Olives - Morracan Dired', '€69,17');
insert into articulos (id, nombre, precio) values (650, 'Ostrich - Prime Cut', '€66,39');
insert into articulos (id, nombre, precio) values (651, 'Schnappes Peppermint - Walker', '€85,44');
insert into articulos (id, nombre, precio) values (652, 'Oil - Margarine', '€75,25');
insert into articulos (id, nombre, precio) values (653, 'Chef Hat 20cm', '€84,38');
insert into articulos (id, nombre, precio) values (654, 'Turkey - Whole, Fresh', '€97,56');
insert into articulos (id, nombre, precio) values (655, 'Isomalt', '€41,89');
insert into articulos (id, nombre, precio) values (656, 'Tea - Darjeeling, Azzura', '€73,24');
insert into articulos (id, nombre, precio) values (657, 'Wine - Red, Concha Y Toro', '€38,41');
insert into articulos (id, nombre, precio) values (658, 'Toothpick Frilled', '€37,21');
insert into articulos (id, nombre, precio) values (659, 'Veal - Heart', '€15,66');
insert into articulos (id, nombre, precio) values (660, 'Squash - Pattypan, Yellow', '€24,57');
insert into articulos (id, nombre, precio) values (661, 'Juice - Propel Sport', '€31,93');
insert into articulos (id, nombre, precio) values (662, 'Soy Protein', '€26,51');
insert into articulos (id, nombre, precio) values (663, 'Calypso - Black Cherry Lemonade', '€99,48');
insert into articulos (id, nombre, precio) values (664, 'Ocean Spray - Kiwi Strawberry', '€85,13');
insert into articulos (id, nombre, precio) values (665, 'Grapes - Green', '€49,08');
insert into articulos (id, nombre, precio) values (666, 'Cheese - Camembert', '€90,18');
insert into articulos (id, nombre, precio) values (667, 'Wine - Magnotta - Cab Franc', '€52,87');
insert into articulos (id, nombre, precio) values (668, 'Pate Pans Yellow', '€82,45');
insert into articulos (id, nombre, precio) values (669, 'Peppercorns - Green', '€19,47');
insert into articulos (id, nombre, precio) values (670, 'Tomatoes - Cherry', '€84,18');
insert into articulos (id, nombre, precio) values (671, 'Five Alive Citrus', '€50,00');
insert into articulos (id, nombre, precio) values (672, 'Coffee - Ristretto Coffee Capsule', '€89,09');
insert into articulos (id, nombre, precio) values (673, 'Beets - Golden', '€23,95');
insert into articulos (id, nombre, precio) values (674, 'Salt And Pepper Mix - Black', '€64,46');
insert into articulos (id, nombre, precio) values (675, 'Pork - Loin, Boneless', '€32,49');
insert into articulos (id, nombre, precio) values (676, 'Sobe - Tropical Energy', '€24,01');
insert into articulos (id, nombre, precio) values (677, 'Mayonnaise', '€93,26');
insert into articulos (id, nombre, precio) values (678, 'Wine - Chateau Bonnet', '€29,11');
insert into articulos (id, nombre, precio) values (679, 'Bread - Multigrain Oval', '€39,50');
insert into articulos (id, nombre, precio) values (680, 'Vinegar - Tarragon', '€22,35');
insert into articulos (id, nombre, precio) values (681, 'Scallops 60/80 Iqf', '€74,04');
insert into articulos (id, nombre, precio) values (682, 'General Purpose Trigger', '€76,23');
insert into articulos (id, nombre, precio) values (683, 'Chinese Lemon Pork', '€20,78');
insert into articulos (id, nombre, precio) values (684, 'Roe - Flying Fish', '€18,46');
insert into articulos (id, nombre, precio) values (685, 'Gloves - Goldtouch Disposable', '€90,85');
insert into articulos (id, nombre, precio) values (686, 'Flour - Semolina', '€84,26');
insert into articulos (id, nombre, precio) values (687, 'Sherbet - Raspberry', '€60,02');
insert into articulos (id, nombre, precio) values (688, 'Chilli Paste, Ginger Garlic', '€57,98');
insert into articulos (id, nombre, precio) values (689, 'Beer - True North Strong Ale', '€37,76');
insert into articulos (id, nombre, precio) values (690, 'Pork - Suckling Pig', '€73,38');
insert into articulos (id, nombre, precio) values (691, 'Pork - Backs - Boneless', '€61,41');
insert into articulos (id, nombre, precio) values (692, 'Chinese Foods - Pepper Beef', '€62,18');
insert into articulos (id, nombre, precio) values (693, 'Tomatoes - Grape', '€16,80');
insert into articulos (id, nombre, precio) values (694, 'Beans - French', '€66,92');
insert into articulos (id, nombre, precio) values (695, 'Sprouts - Onion', '€87,43');
insert into articulos (id, nombre, precio) values (696, 'Gherkin - Sour', '€31,49');
insert into articulos (id, nombre, precio) values (697, 'Chocolate - Unsweetened', '€49,09');
insert into articulos (id, nombre, precio) values (698, 'Pork - Caul Fat', '€43,03');
insert into articulos (id, nombre, precio) values (699, 'Yoplait - Strawbrasp Peac', '€77,66');
insert into articulos (id, nombre, precio) values (700, 'Bread - Bagels, Plain', '€37,69');
insert into articulos (id, nombre, precio) values (701, 'Bread - White Epi Baguette', '€60,21');
insert into articulos (id, nombre, precio) values (702, 'Soup - Campbells Asian Noodle', '€77,42');
insert into articulos (id, nombre, precio) values (703, 'Anchovy In Oil', '€88,48');
insert into articulos (id, nombre, precio) values (704, 'Island Oasis - Wildberry', '€89,31');
insert into articulos (id, nombre, precio) values (705, 'Wine - Semi Dry Riesling Vineland', '€50,36');
insert into articulos (id, nombre, precio) values (706, 'Tomato - Green', '€73,83');
insert into articulos (id, nombre, precio) values (707, 'Wine - Carmenere Casillero Del', '€17,42');
insert into articulos (id, nombre, precio) values (708, 'Cheese - Colby', '€37,04');
insert into articulos (id, nombre, precio) values (709, 'Ice Cream Bar - Hageen Daz To', '€28,90');
insert into articulos (id, nombre, precio) values (710, 'Gatorade - Fruit Punch', '€92,18');
insert into articulos (id, nombre, precio) values (711, 'Cookie Choc', '€27,92');
insert into articulos (id, nombre, precio) values (712, 'Cucumber - English', '€70,37');
insert into articulos (id, nombre, precio) values (713, 'Ice Cream - Vanilla', '€54,78');
insert into articulos (id, nombre, precio) values (714, 'Tea - Mint', '€88,31');
insert into articulos (id, nombre, precio) values (715, 'Steam Pan Full Lid', '€75,91');
insert into articulos (id, nombre, precio) values (716, 'Lemonade - Strawberry, 591 Ml', '€68,06');
insert into articulos (id, nombre, precio) values (717, 'Cup - Translucent 7 Oz Clear', '€32,79');
insert into articulos (id, nombre, precio) values (718, 'V8 Splash Strawberry Banana', '€67,77');
insert into articulos (id, nombre, precio) values (719, 'Table Cloth 62x114 White', '€78,58');
insert into articulos (id, nombre, precio) values (720, 'Cheese - Colby', '€19,71');
insert into articulos (id, nombre, precio) values (721, 'Sausage - Chorizo', '€81,93');
insert into articulos (id, nombre, precio) values (722, 'Grapefruit - Pink', '€19,48');
insert into articulos (id, nombre, precio) values (723, 'Bread - Pullman, Sliced', '€18,01');
insert into articulos (id, nombre, precio) values (724, 'Pumpkin', '€16,70');
insert into articulos (id, nombre, precio) values (725, 'Beef - Tenderlion, Center Cut', '€45,00');
insert into articulos (id, nombre, precio) values (726, 'Sprouts - Baby Pea Tendrils', '€91,17');
insert into articulos (id, nombre, precio) values (727, 'Puree - Raspberry', '€53,55');
insert into articulos (id, nombre, precio) values (728, 'Table Cloth 62x114 White', '€37,12');
insert into articulos (id, nombre, precio) values (729, 'Crab - Blue, Frozen', '€25,74');
insert into articulos (id, nombre, precio) values (730, 'Sauce - Apple, Unsweetened', '€68,22');
insert into articulos (id, nombre, precio) values (731, 'Juice - Happy Planet', '€61,86');
insert into articulos (id, nombre, precio) values (732, 'Tea - Darjeeling, Azzura', '€59,74');
insert into articulos (id, nombre, precio) values (733, 'Cookie - Oreo 100x2', '€31,65');
insert into articulos (id, nombre, precio) values (734, 'Ecolab - Mikroklene 4/4 L', '€45,81');
insert into articulos (id, nombre, precio) values (735, 'Pastry - Plain Baked Croissant', '€96,49');
insert into articulos (id, nombre, precio) values (736, 'Lid - High Heat, Super Clear', '€94,95');
insert into articulos (id, nombre, precio) values (737, 'Wine - Gewurztraminer Pierre', '€72,90');
insert into articulos (id, nombre, precio) values (738, 'Vector Energy Bar', '€28,26');
insert into articulos (id, nombre, precio) values (739, 'Cinnamon - Ground', '€51,41');
insert into articulos (id, nombre, precio) values (740, 'Plate - Foam, Bread And Butter', '€93,36');
insert into articulos (id, nombre, precio) values (741, 'Cheese - Valancey', '€38,84');
insert into articulos (id, nombre, precio) values (742, 'Juice - Apple, 1.36l', '€51,46');
insert into articulos (id, nombre, precio) values (743, 'Wine - Guy Sage Touraine', '€38,80');
insert into articulos (id, nombre, precio) values (744, 'Syrup - Monin - Blue Curacao', '€70,86');
insert into articulos (id, nombre, precio) values (745, 'Compound - Raspberry', '€17,18');
insert into articulos (id, nombre, precio) values (746, 'Syrup - Monin, Amaretta', '€65,53');
insert into articulos (id, nombre, precio) values (747, 'Container - Hngd Cll Blk 7x7x3', '€71,33');
insert into articulos (id, nombre, precio) values (748, 'Huck White Towels', '€99,04');
insert into articulos (id, nombre, precio) values (749, 'Beets - Candy Cane, Organic', '€64,97');
insert into articulos (id, nombre, precio) values (750, 'Vinegar - Sherry', '€82,07');
insert into articulos (id, nombre, precio) values (751, 'Cheese - Stilton', '€67,82');
insert into articulos (id, nombre, precio) values (752, 'Sauce - Hollandaise', '€42,11');
insert into articulos (id, nombre, precio) values (753, 'Cheese - Pied De Vents', '€80,28');
insert into articulos (id, nombre, precio) values (754, 'Carbonated Water - Cherry', '€20,56');
insert into articulos (id, nombre, precio) values (755, 'Carrots - Purple, Organic', '€60,13');
insert into articulos (id, nombre, precio) values (756, 'Chicken - White Meat, No Tender', '€21,32');
insert into articulos (id, nombre, precio) values (757, 'Fish - Bones', '€57,45');
insert into articulos (id, nombre, precio) values (758, 'Table Cloth 120 Round White', '€92,69');
insert into articulos (id, nombre, precio) values (759, 'Rice Paper', '€93,30');
insert into articulos (id, nombre, precio) values (760, 'Trout - Rainbow, Fresh', '€35,55');
insert into articulos (id, nombre, precio) values (761, 'Crackers - Soda / Saltins', '€23,28');
insert into articulos (id, nombre, precio) values (762, 'Wine - Charddonnay Errazuriz', '€88,30');
insert into articulos (id, nombre, precio) values (763, 'Coconut - Shredded, Unsweet', '€54,43');
insert into articulos (id, nombre, precio) values (764, 'Chef Hat 25cm', '€43,34');
insert into articulos (id, nombre, precio) values (765, 'Gelatine Powder', '€69,88');
insert into articulos (id, nombre, precio) values (766, 'Pastry - Chocolate Marble Tea', '€99,31');
insert into articulos (id, nombre, precio) values (767, 'Peas - Pigeon, Dry', '€34,38');
insert into articulos (id, nombre, precio) values (768, 'Pepper - Chipotle, Canned', '€24,03');
insert into articulos (id, nombre, precio) values (769, 'Gatorade - Cool Blue Raspberry', '€54,91');
insert into articulos (id, nombre, precio) values (770, 'Cinnamon Buns Sticky', '€74,35');
insert into articulos (id, nombre, precio) values (771, 'Pernod', '€85,13');
insert into articulos (id, nombre, precio) values (772, 'Pork - Back, Short Cut, Boneless', '€58,45');
insert into articulos (id, nombre, precio) values (773, 'Bread - White, Unsliced', '€94,67');
insert into articulos (id, nombre, precio) values (774, 'Appetizer - Sausage Rolls', '€73,06');
insert into articulos (id, nombre, precio) values (775, 'Corn Shoots', '€72,34');
insert into articulos (id, nombre, precio) values (776, 'Lamb - Sausage Casings', '€95,08');
insert into articulos (id, nombre, precio) values (777, 'Table Cloth 62x114 White', '€58,20');
insert into articulos (id, nombre, precio) values (778, 'Wine - Domaine Boyar Royal', '€31,13');
insert into articulos (id, nombre, precio) values (779, 'Raisin - Golden', '€33,24');
insert into articulos (id, nombre, precio) values (780, 'Cheese - Brick With Pepper', '€80,34');
insert into articulos (id, nombre, precio) values (781, 'White Fish - Filets', '€34,06');
insert into articulos (id, nombre, precio) values (782, 'Pimento - Canned', '€92,06');
insert into articulos (id, nombre, precio) values (783, 'Oil - Margarine', '€47,83');
insert into articulos (id, nombre, precio) values (784, 'Lemonade - Island Tea, 591 Ml', '€79,88');
insert into articulos (id, nombre, precio) values (785, 'Wine - Pinot Grigio Collavini', '€77,44');
insert into articulos (id, nombre, precio) values (786, 'Soupfoamcont12oz 112con', '€91,29');
insert into articulos (id, nombre, precio) values (787, 'Pork - Smoked Kassler', '€50,63');
insert into articulos (id, nombre, precio) values (788, 'Lobak', '€62,48');
insert into articulos (id, nombre, precio) values (789, 'Beer - Upper Canada Lager', '€91,95');
insert into articulos (id, nombre, precio) values (790, 'Skewers - Bamboo', '€96,09');
insert into articulos (id, nombre, precio) values (791, 'Cheese - Mozzarella', '€88,46');
insert into articulos (id, nombre, precio) values (792, 'Ostrich - Fan Fillet', '€53,29');
insert into articulos (id, nombre, precio) values (793, 'Chilli Paste, Hot Sambal Oelek', '€77,24');
insert into articulos (id, nombre, precio) values (794, 'Wine - Carmenere Casillero Del', '€69,26');
insert into articulos (id, nombre, precio) values (795, 'Turnip - White, Organic', '€33,49');
insert into articulos (id, nombre, precio) values (796, 'Wine - Malbec Trapiche Reserve', '€76,72');
insert into articulos (id, nombre, precio) values (797, 'Beef - Salted', '€75,48');
insert into articulos (id, nombre, precio) values (798, 'Wine - Acient Coast Caberne', '€54,85');
insert into articulos (id, nombre, precio) values (799, 'Oil - Food, Lacquer Spray', '€52,38');
insert into articulos (id, nombre, precio) values (800, 'Jam - Raspberry,jar', '€54,58');
insert into articulos (id, nombre, precio) values (801, 'Cookies - Fortune', '€78,86');
insert into articulos (id, nombre, precio) values (802, 'Juice - Cranberry 284ml', '€81,43');
insert into articulos (id, nombre, precio) values (803, 'Sauce - Soya, Dark', '€76,00');
insert into articulos (id, nombre, precio) values (804, 'Ice Cream - Strawberry', '€94,05');
insert into articulos (id, nombre, precio) values (805, 'Coffee Decaf Colombian', '€45,24');
insert into articulos (id, nombre, precio) values (806, 'Veal - Shank, Pieces', '€97,80');
insert into articulos (id, nombre, precio) values (807, 'Ecolab - Ster Bac', '€94,65');
insert into articulos (id, nombre, precio) values (808, 'Pears - Fiorelle', '€44,42');
insert into articulos (id, nombre, precio) values (809, 'Wine - Red Oakridge Merlot', '€52,90');
insert into articulos (id, nombre, precio) values (810, 'Pork - Sausage, Medium', '€61,85');
insert into articulos (id, nombre, precio) values (811, 'Plums - Red', '€87,23');
insert into articulos (id, nombre, precio) values (812, 'Veal - Insides Provini', '€69,35');
insert into articulos (id, nombre, precio) values (813, 'Cheese - St. Andre', '€68,30');
insert into articulos (id, nombre, precio) values (814, 'Dc Hikiage Hira Huba', '€56,01');
insert into articulos (id, nombre, precio) values (815, 'Carrots - Mini Red Organic', '€95,83');
insert into articulos (id, nombre, precio) values (816, 'Quail Eggs - Canned', '€42,81');
insert into articulos (id, nombre, precio) values (817, 'Soup - Campbells, Butternut', '€80,64');
insert into articulos (id, nombre, precio) values (818, 'Wine - Remy Pannier Rose', '€58,33');
insert into articulos (id, nombre, precio) values (819, 'Vaccum Bag 10x13', '€96,61');
insert into articulos (id, nombre, precio) values (820, 'Potato - Sweet', '€59,72');
insert into articulos (id, nombre, precio) values (821, 'Wine - Delicato Merlot', '€49,19');
insert into articulos (id, nombre, precio) values (822, 'Cod - Fillets', '€40,07');
insert into articulos (id, nombre, precio) values (823, 'Cheese - Wine', '€49,22');
insert into articulos (id, nombre, precio) values (824, 'Wine - Ej Gallo Sonoma', '€49,06');
insert into articulos (id, nombre, precio) values (825, 'Lettuce - Lolla Rosa', '€51,82');
insert into articulos (id, nombre, precio) values (826, 'Tea - Black Currant', '€22,70');
insert into articulos (id, nombre, precio) values (827, 'Mountain Dew', '€56,76');
insert into articulos (id, nombre, precio) values (828, 'Lamb - Bones', '€37,34');
insert into articulos (id, nombre, precio) values (829, 'Steel Wool S.o.s', '€91,28');
insert into articulos (id, nombre, precio) values (830, 'Ostrich - Prime Cut', '€80,49');
insert into articulos (id, nombre, precio) values (831, 'Sunflower Seed Raw', '€86,02');
insert into articulos (id, nombre, precio) values (832, 'Bag - Regular Kraft 20 Lb', '€91,62');
insert into articulos (id, nombre, precio) values (833, 'Bread - Frozen Basket Variety', '€58,35');
insert into articulos (id, nombre, precio) values (834, 'Mcguinness - Blue Curacao', '€92,92');
insert into articulos (id, nombre, precio) values (835, 'Monkfish - Fresh', '€77,97');
insert into articulos (id, nombre, precio) values (836, 'Tea - Lemon Green Tea', '€59,35');
insert into articulos (id, nombre, precio) values (837, 'Boogies', '€87,71');
insert into articulos (id, nombre, precio) values (838, 'Crackers - Graham', '€40,07');
insert into articulos (id, nombre, precio) values (839, 'Beef - Short Loin', '€67,20');
insert into articulos (id, nombre, precio) values (840, 'Cheese - Mozzarella, Buffalo', '€95,01');
insert into articulos (id, nombre, precio) values (841, 'Bread - French Stick', '€59,23');
insert into articulos (id, nombre, precio) values (842, 'Foie Gras', '€58,69');
insert into articulos (id, nombre, precio) values (843, 'Mangostein', '€80,71');
insert into articulos (id, nombre, precio) values (844, 'Broom - Angled', '€92,11');
insert into articulos (id, nombre, precio) values (845, 'Oneshot Automatic Soap System', '€96,08');
insert into articulos (id, nombre, precio) values (846, 'Sobe - Liz Blizz', '€80,05');
insert into articulos (id, nombre, precio) values (847, 'Pork - Backs - Boneless', '€97,42');
insert into articulos (id, nombre, precio) values (848, 'Carbonated Water - Peach', '€88,73');
insert into articulos (id, nombre, precio) values (849, 'Chinese Foods - Chicken', '€70,62');
insert into articulos (id, nombre, precio) values (850, 'Tuna - Sushi Grade', '€41,54');
insert into articulos (id, nombre, precio) values (851, 'Sauce - Fish 25 Ozf Bottle', '€48,93');
insert into articulos (id, nombre, precio) values (852, 'Bread - Multigrain', '€84,59');
insert into articulos (id, nombre, precio) values (853, 'Pepper - Paprika, Hungarian', '€48,17');
insert into articulos (id, nombre, precio) values (854, 'Island Oasis - Cappucino Mix', '€94,78');
insert into articulos (id, nombre, precio) values (855, 'White Fish - Filets', '€60,94');
insert into articulos (id, nombre, precio) values (856, 'Bread - Onion Focaccia', '€76,70');
insert into articulos (id, nombre, precio) values (857, 'Pineapple - Regular', '€84,55');
insert into articulos (id, nombre, precio) values (858, 'Capers - Ox Eye Daisy', '€92,67');
insert into articulos (id, nombre, precio) values (859, 'Soup - Campbells - Chicken Noodle', '€45,77');
insert into articulos (id, nombre, precio) values (860, 'Wine - Magnotta, White', '€35,03');
insert into articulos (id, nombre, precio) values (861, 'Flour - Semolina', '€76,63');
insert into articulos (id, nombre, precio) values (862, 'Soup - Chicken And Wild Rice', '€95,06');
insert into articulos (id, nombre, precio) values (863, 'Bacardi Breezer - Tropical', '€35,37');
insert into articulos (id, nombre, precio) values (864, 'Phyllo Dough', '€16,63');
insert into articulos (id, nombre, precio) values (865, 'Longos - Chicken Wings', '€26,36');
insert into articulos (id, nombre, precio) values (866, 'Miso Paste White', '€47,99');
insert into articulos (id, nombre, precio) values (867, 'Sea Bass - Fillets', '€36,40');
insert into articulos (id, nombre, precio) values (868, 'Cherries - Maraschino,jar', '€30,52');
insert into articulos (id, nombre, precio) values (869, 'Oil - Sunflower', '€21,37');
insert into articulos (id, nombre, precio) values (870, 'Pasta - Fettuccine, Dry', '€23,10');
insert into articulos (id, nombre, precio) values (871, 'Everfresh Products', '€30,68');
insert into articulos (id, nombre, precio) values (872, 'Pasta - Shells, Medium, Dry', '€52,47');
insert into articulos (id, nombre, precio) values (873, 'Lamb - Loin Chops', '€94,80');
insert into articulos (id, nombre, precio) values (874, 'Snails - Large Canned', '€17,72');
insert into articulos (id, nombre, precio) values (875, 'Turnip - White', '€75,14');
insert into articulos (id, nombre, precio) values (876, 'Beef - Cooked, Corned', '€18,23');
insert into articulos (id, nombre, precio) values (877, 'Sobe - Berry Energy', '€19,04');
insert into articulos (id, nombre, precio) values (878, 'Beer - Mill St Organic', '€84,93');
insert into articulos (id, nombre, precio) values (879, 'Onions - Green', '€45,29');
insert into articulos (id, nombre, precio) values (880, 'Beans - Fine', '€40,99');
insert into articulos (id, nombre, precio) values (881, 'Pate - Cognac', '€89,67');
insert into articulos (id, nombre, precio) values (882, 'Chestnuts - Whole,canned', '€27,33');
insert into articulos (id, nombre, precio) values (883, 'Milk Powder', '€90,12');
insert into articulos (id, nombre, precio) values (884, 'Soda Water - Club Soda, 355 Ml', '€77,23');
insert into articulos (id, nombre, precio) values (885, 'Mushroom - Chanterelle Frozen', '€89,60');
insert into articulos (id, nombre, precio) values (886, 'Tarragon - Primerba, Paste', '€96,42');
insert into articulos (id, nombre, precio) values (887, 'Bag Stand', '€32,56');
insert into articulos (id, nombre, precio) values (888, 'Vol Au Vents', '€19,40');
insert into articulos (id, nombre, precio) values (889, 'Shrimp - Black Tiger 8 - 12', '€17,52');
insert into articulos (id, nombre, precio) values (890, 'Beer - Sleemans Honey Brown', '€64,60');
insert into articulos (id, nombre, precio) values (891, 'Tomato - Green', '€68,50');
insert into articulos (id, nombre, precio) values (892, 'Lemonade - Island Tea, 591 Ml', '€21,16');
insert into articulos (id, nombre, precio) values (893, 'Fudge - Chocolate Fudge', '€55,51');
insert into articulos (id, nombre, precio) values (894, 'Lid Tray - 12in Dome', '€68,23');
insert into articulos (id, nombre, precio) values (895, 'Nutmeg - Ground', '€32,50');
insert into articulos (id, nombre, precio) values (896, 'Wine - Mondavi Coastal Private', '€78,62');
insert into articulos (id, nombre, precio) values (897, 'Vermouth - White, Cinzano', '€37,38');
insert into articulos (id, nombre, precio) values (898, 'Wine - Redchard Merritt', '€85,58');
insert into articulos (id, nombre, precio) values (899, 'Tea - Decaf 1 Cup', '€56,22');
insert into articulos (id, nombre, precio) values (900, 'Nori Sea Weed - Gold Label', '€42,14');
insert into articulos (id, nombre, precio) values (901, 'Pasta - Fettuccine, Dry', '€56,04');
insert into articulos (id, nombre, precio) values (902, 'Table Cloth 90x90 White', '€41,55');
insert into articulos (id, nombre, precio) values (903, 'Sauce Tomato Pouch', '€96,79');
insert into articulos (id, nombre, precio) values (904, 'Split Peas - Yellow, Dry', '€54,74');
insert into articulos (id, nombre, precio) values (905, 'Kiwi', '€36,40');
insert into articulos (id, nombre, precio) values (906, 'Strawberries', '€30,84');
insert into articulos (id, nombre, precio) values (907, 'Pepper - Green Thai', '€33,09');
insert into articulos (id, nombre, precio) values (908, 'Wine - Black Tower Qr', '€18,04');
insert into articulos (id, nombre, precio) values (909, 'Puff Pastry - Sheets', '€79,21');
insert into articulos (id, nombre, precio) values (910, 'Pasta - Penne Primavera, Single', '€84,57');
insert into articulos (id, nombre, precio) values (911, 'Wine - Red, Lurton Merlot De', '€57,63');
insert into articulos (id, nombre, precio) values (912, 'Pasta - Fettuccine, Egg, Fresh', '€97,68');
insert into articulos (id, nombre, precio) values (913, 'Ginsing - Fresh', '€96,75');
insert into articulos (id, nombre, precio) values (914, 'Seedlings - Buckwheat, Organic', '€71,38');
insert into articulos (id, nombre, precio) values (915, 'Beer - Rickards Red', '€63,14');
insert into articulos (id, nombre, precio) values (916, 'Beer - Blue', '€93,95');
insert into articulos (id, nombre, precio) values (917, 'Compound - Pear', '€94,46');
insert into articulos (id, nombre, precio) values (918, 'Soup - Base Broth Chix', '€72,53');
insert into articulos (id, nombre, precio) values (919, 'Salt - Table', '€71,50');
insert into articulos (id, nombre, precio) values (920, 'Kiwano', '€48,36');
insert into articulos (id, nombre, precio) values (921, 'Crackers - Trio', '€86,62');
insert into articulos (id, nombre, precio) values (922, 'Veal - Knuckle', '€85,15');
insert into articulos (id, nombre, precio) values (923, 'Bar Mix - Lemon', '€27,50');
insert into articulos (id, nombre, precio) values (924, 'Aspic - Clear', '€70,23');
insert into articulos (id, nombre, precio) values (925, 'Venison - Striploin', '€21,72');
insert into articulos (id, nombre, precio) values (926, 'Appetizer - Mini Egg Roll, Shrimp', '€35,38');
insert into articulos (id, nombre, precio) values (927, 'Cherries - Maraschino,jar', '€38,88');
insert into articulos (id, nombre, precio) values (928, 'Coffee Caramel Biscotti', '€62,35');
insert into articulos (id, nombre, precio) values (929, 'Chutney Sauce', '€46,98');
insert into articulos (id, nombre, precio) values (930, 'Bread - White Mini Epi', '€98,82');
insert into articulos (id, nombre, precio) values (931, 'Tray - 16in Rnd Blk', '€65,85');
insert into articulos (id, nombre, precio) values (932, 'Bread - Pumpernickel', '€66,49');
insert into articulos (id, nombre, precio) values (933, 'Scampi Tail', '€22,92');
insert into articulos (id, nombre, precio) values (934, 'Pear - Halves', '€50,23');
insert into articulos (id, nombre, precio) values (935, 'Milk - 2% 250 Ml', '€69,35');
insert into articulos (id, nombre, precio) values (936, 'Chicken - White Meat, No Tender', '€34,83');
insert into articulos (id, nombre, precio) values (937, 'Mop Head - Cotton, 24 Oz', '€83,92');
insert into articulos (id, nombre, precio) values (938, 'Veal - Chops, Split, Frenched', '€67,37');
insert into articulos (id, nombre, precio) values (939, 'Lettuce - Baby Salad Greens', '€86,10');
insert into articulos (id, nombre, precio) values (940, 'Soup - Campbells, Spinach Crm', '€24,16');
insert into articulos (id, nombre, precio) values (941, 'Oregano - Fresh', '€18,73');
insert into articulos (id, nombre, precio) values (942, 'Coffee Swiss Choc Almond', '€20,41');
insert into articulos (id, nombre, precio) values (943, 'Table Cloth 62x120 Colour', '€80,13');
insert into articulos (id, nombre, precio) values (944, 'Container - Hngd Cll Blk 7x7x3', '€69,71');
insert into articulos (id, nombre, precio) values (945, 'Salami - Genova', '€44,65');
insert into articulos (id, nombre, precio) values (946, 'Table Cloth 120 Round White', '€77,62');
insert into articulos (id, nombre, precio) values (947, 'Pork - Liver', '€81,77');
insert into articulos (id, nombre, precio) values (948, 'Nut - Almond, Blanched, Sliced', '€37,38');
insert into articulos (id, nombre, precio) values (949, 'Appetizer - Cheese Bites', '€75,63');
insert into articulos (id, nombre, precio) values (950, 'Energy Drink - Franks Original', '€62,39');
insert into articulos (id, nombre, precio) values (951, 'Water, Tap', '€22,52');
insert into articulos (id, nombre, precio) values (952, 'Doilies - 5, Paper', '€39,75');
insert into articulos (id, nombre, precio) values (953, 'Foil Wrap', '€71,19');
insert into articulos (id, nombre, precio) values (954, 'Glaze - Apricot', '€37,24');
insert into articulos (id, nombre, precio) values (955, 'Milk - Chocolate 500ml', '€60,00');
insert into articulos (id, nombre, precio) values (956, 'Veal - Leg, Provimi - 50 Lb Max', '€26,59');
insert into articulos (id, nombre, precio) values (957, 'Cheese Cheddar Processed', '€98,35');
insert into articulos (id, nombre, precio) values (958, 'Pineapple - Golden', '€52,38');
insert into articulos (id, nombre, precio) values (959, 'Apple - Delicious, Red', '€30,82');
insert into articulos (id, nombre, precio) values (960, 'Artichoke - Hearts, Canned', '€38,18');
insert into articulos (id, nombre, precio) values (961, 'Potatoes - Mini White 3 Oz', '€88,05');
insert into articulos (id, nombre, precio) values (962, 'Wine - Shiraz South Eastern', '€17,95');
insert into articulos (id, nombre, precio) values (963, 'Flour - Teff', '€81,68');
insert into articulos (id, nombre, precio) values (964, 'Cake Circle, Paprus', '€93,51');
insert into articulos (id, nombre, precio) values (965, 'Tea - Lemon Scented', '€44,33');
insert into articulos (id, nombre, precio) values (966, 'Rice Wine - Aji Mirin', '€54,20');
insert into articulos (id, nombre, precio) values (967, 'Flavouring Vanilla Artificial', '€31,44');
insert into articulos (id, nombre, precio) values (968, 'Artichokes - Knobless, White', '€82,04');
insert into articulos (id, nombre, precio) values (969, 'Cocktail Napkin Blue', '€80,14');
insert into articulos (id, nombre, precio) values (970, 'Wine - Pinot Noir Latour', '€34,40');
insert into articulos (id, nombre, precio) values (971, 'Puff Pastry - Sheets', '€74,90');
insert into articulos (id, nombre, precio) values (972, 'Chips Potato Salt Vinegar 43g', '€45,80');
insert into articulos (id, nombre, precio) values (973, 'Pork - Tenderloin, Fresh', '€88,43');
insert into articulos (id, nombre, precio) values (974, 'Cheese - Feta', '€35,32');
insert into articulos (id, nombre, precio) values (975, 'Pepper - White, Whole', '€54,51');
insert into articulos (id, nombre, precio) values (976, 'Calypso - Pineapple Passion', '€49,38');
insert into articulos (id, nombre, precio) values (977, 'Flavouring - Raspberry', '€38,84');
insert into articulos (id, nombre, precio) values (978, 'Appetizer - Smoked Salmon / Dill', '€46,77');
insert into articulos (id, nombre, precio) values (979, 'Lettuce - Lambs Mash', '€46,77');
insert into articulos (id, nombre, precio) values (980, 'Truffle - Whole Black Peeled', '€86,59');
insert into articulos (id, nombre, precio) values (981, 'Guava', '€59,74');
insert into articulos (id, nombre, precio) values (982, 'Pork - Bones', '€96,06');
insert into articulos (id, nombre, precio) values (983, 'Pork - Backs - Boneless', '€40,42');
insert into articulos (id, nombre, precio) values (984, 'Huck White Towels', '€48,64');
insert into articulos (id, nombre, precio) values (985, 'Chocolate - Milk Coating', '€95,03');
insert into articulos (id, nombre, precio) values (986, 'Nut - Pistachio, Shelled', '€16,66');
insert into articulos (id, nombre, precio) values (987, 'Scampi Tail', '€95,40');
insert into articulos (id, nombre, precio) values (988, 'Clam - Cherrystone', '€67,45');
insert into articulos (id, nombre, precio) values (989, 'Table Cloth 62x120 White', '€53,42');
insert into articulos (id, nombre, precio) values (990, 'Crab - Meat', '€33,10');
insert into articulos (id, nombre, precio) values (991, 'Sansho Powder', '€99,15');
insert into articulos (id, nombre, precio) values (992, 'Sterno - Chafing Dish Fuel', '€70,00');
insert into articulos (id, nombre, precio) values (993, 'Bacardi Breezer - Tropical', '€30,94');
insert into articulos (id, nombre, precio) values (994, 'Lettuce - Mini Greens, Whole', '€64,96');
insert into articulos (id, nombre, precio) values (995, 'Pail - 15l White, With Handle', '€22,13');
insert into articulos (id, nombre, precio) values (996, 'Juice - Orange 1.89l', '€90,32');
insert into articulos (id, nombre, precio) values (997, 'Truffle Cups Green', '€51,95');
insert into articulos (id, nombre, precio) values (998, 'Beans - Wax', '€18,67');
insert into articulos (id, nombre, precio) values (999, 'Lentils - Red, Dry', '€24,24');
insert into articulos (id, nombre, precio) values (1000, 'Wine - Barbera Alba Doc 2001', '€91,44');
